version: "3"

services:
  wordpress:
    build:
      context: .Docker/wordpress/
      args:
        WORDPRESS_VERSION=${WORDPRESS_VERSION}
  mysql:
    build:
      context: .Docker/mysql/
      args:
        MYSQL_VERSION=${MYSQL_VERSION}