version: "3"

services:
  wordpress:
    container_name: docker_for_wordpress_wordpress
    env_file:
      - .env
    build:
      context: .Docker/wordpress/
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION}
    volumes:
      - ./html:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
      - WORDPRESS_DB_HOST=${MYSQL_HOST}
#      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - WORDPRESS_TABLE_PREFIX=
#      - WORDPRESS_AUTH_KEY=
#      - WORDPRESS_SECURE_AUTH_KEY=
#      - WORDPRESS_LOGGED_IN_KEY=
#      - WORDPRESS_NONCE_KEY=
#      - WORDPRESS_AUTH_SALT
#      - WORDPRESS_SECURE_AUTH_SALT=
#      - WORDPRESS_LOGGED_IN_SALT=
#      - WORDPRESS_NONCE_SALT=
      - WORDPRESS_DEBUG=1
#      - WORDPRESS_CONFIG_EXTRA=
    ports:
      - ${WORDPRESS_PORT}:80
    depends_on:
      - mysql

  mysql:
    container_name: docker_for_wordpress_mysql
    env_file:
      - .env
    build:
      context: .Docker/mysql/
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    volumes:
      - ./.Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    privileged: true
    ports:
      - ${MYSQL_PORT}:3306

#volumes:
#  wordpress:
#  mysql: